### ISSUE TITLE
New ports

### ISSUE THREAD

**Issue by cracyc** [tenox7/aclock#1]
Aclock for Convergent CTOS
[aclock-ctos.zip](https://github.com/tenox7/aclock/files/870326/aclock-ctos.zip)

Aclock for iRMX, binary is for iRMX II 286
[ACLOCK-irmx.zip](https://github.com/tenox7/aclock/files/870327/ACLOCK-irmx.zip)

**Comment by tenox7** [comment]
Thank you! I have added it to the incoming queue and process with other entries! Any chance for a picture of physical machine running these? Or have you build these on an emulator?

**Comment by cracyc** [comment]
Both from emulators.  I know of only one person who has an 286 Intel system 310 that can run iRMX but he's way to busy to try and do that (and since it has no video output it wouldn't look much different anyway).  CTOS is just from the 386AT version, the floppies are from bitsavers.  The binary should work on the Burroughs Ngen but I don't have one to test.  I'm also going to try to compile it for the Olivetti M20 which is interesting as, I believe, the only widely available Zilog Z8000 computer, there's a cross compiler at [http://www.z80ne.com/m20/sections/download/z8kgcc/z8kgcc.html](http://www.z80ne.com/m20/sections/download/z8kgcc/z8kgcc.html).

**Comment by cracyc** [comment]
Here's an M20 PCOS port.
[aclock-m20-pcos.zip](https://github.com/tenox7/aclock/files/901197/aclock-m20-pcos.zip)
It seems to only work on PCOS 2+, possibly a limitation of the c library.

**Comment by plainspooky** [comment]
Is necessary to new ports be written in C?

**Comment by tenox7** [comment]
Great question. I would say that Aclock should be written in language that is most native to the given platform. Most operating systems are written in C hence the choice of language. However if a certain operating system is written in another language then by all means yes. For instance Singularity OS is a C# monstrosity and therefore uses C# version of Aclock. Similarly if you were to port Aclock to a Lisp Machine then it would have to be written in Lisp.

**Comment by plainspooky** [comment]
I created yesterday a pull request for my MSX-DOS version.

**Comment by tenox7** [comment]
Thank you very much! This is very exciting. I going to look at it shortly.

**Comment by plainspooky** [comment]
Nice! I've added both binary and disk image at my forked repository.

**Comment by tenox7** [comment]
Thank you. Apologies for not merging it, I'm currently pre-occupied with another project. I will look in to this in a few days.

**Comment by plainspooky** [comment]
No problems!

**Comment by tenox7** [comment]
@cracyc & @plainspooky can you do a Pull Request to this repo? I think it would be better as you will be credited with it. Thanks!

**Comment by plainspooky** [comment]
Ok!

**Comment by plainspooky** [comment]
A better answer now...I'm going to check the MSX-DOS.... And I'm not sure if have made changes since this PR (I did like the overall performance, so try few improvements. By the way that's a nice idea test my code with Arabic and Korean MSX models as well.

**Comment by tenox7** [comment]
Oh nice!

Also you can easily check if any chances were made using git fetch.

**Comment by plainspooky** [comment]
I submitted a new PR from my forked repo. I've tried to do this directly but got an "ERROR: Permission to tenox7/aclock.git denied to plainspooky"...

**Comment by tenox7** [comment]
pulled! thank you!!!!!!!!!!
